version: 1
project_name: texit
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: api
    main: ./cmd/api/main.go
    binary: texit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ignore:
      - goarch: "386"

  - id: discord
    main: ./cmd/discord/main.go
    binary: texit-discord
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ignore:
      - goarch: "386"

  - id: cli
    main: ./cmd/cli/main.go
    binary: texit-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goarch: "386"

  - id: texit-lambda-sfn-activities
    main: ./cmd/serverless/sfn_activities/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ignore:
      - goarch: "386"

  - id: texit-discord-lambda
    main: ./cmd/serverless/discord/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ignore:
      - goarch: "386"

  - id: texit-discord-callback-lambda
    main: ./cmd/serverless/discord_callback/main.go
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ignore:
      - goarch: "386"

dockers:
  - id: api-arm64
    dockerfile: build/package/api/Dockerfile
    image_templates:
      - "ghcr.io/awlsring/texit:{{.Version}}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64
  - id: api-amd64
    dockerfile: build/package/api/Dockerfile
    image_templates:
      - "ghcr.io/awlsring/texit:{{.Version}}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64
  - id: discord-arm64
    dockerfile: build/package/discord/Dockerfile
    image_templates:
      - "ghcr.io/awlsring/texit-discord:{{.Version}}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64
  - id: discord-amd64
    dockerfile: build/package/discord/Dockerfile
    image_templates:
      - "ghcr.io/awlsring/texit-discord:{{.Version}}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64

docker_manifests:
  - name_template: "ghcr.io/awlsring/texit:{{.Version}}"
    image_templates:
      - "ghcr.io/awlsring/texit:{{.Version}}-amd64"
      - "ghcr.io/awlsring/texit:{{.Version}}-arm64"
  - name_template: "ghcr.io/awlsring/texit:latest"
    image_templates:
      - "ghcr.io/awlsring/texit:{{.Version}}-amd64"
      - "ghcr.io/awlsring/texit:{{.Version}}-arm64"
  - name_template: "ghcr.io/awlsring/texit-discord:{{.Version}}"
    image_templates:
      - "ghcr.io/awlsring/texit:{{.Version}}-amd64"
      - "ghcr.io/awlsring/texit:{{.Version}}-arm64"
  - name_template: "ghcr.io/awlsring/texit-discord:latest"
    image_templates:
      - "ghcr.io/awlsring/texit:{{.Version}}-amd64"
      - "ghcr.io/awlsring/texit:{{.Version}}-arm64"

archives:
  - id: api
    format: tar.gz
    builds: [api]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    allow_different_binary_count: true

  - id: texit-discord-lambda
    format: tar.gz
    builds: [texit-discord-lambda]
    name_template: >-
      {{ .ProjectName }}_discord_lambda_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    allow_different_binary_count: true

  - id: texit-discord-callback-lambda
    format: tar.gz
    builds: [texit-discord-callback-lambda]
    name_template: >-
      {{ .ProjectName }}_discord_callback_lambda_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    allow_different_binary_count: true

  - id: texit-lambda-sfn-activities
    format: tar.gz
    builds: [texit-lambda-sfn-activities]
    name_template: >-
      {{ .ProjectName }}_lambda_sfn_activities_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    allow_different_binary_count: true

  - id: discord
    format: tar.gz
    builds: [discord]
    name_template: >-
      {{ .ProjectName }}_discord_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    allow_different_binary_count: true

  - id: cli
    format: tar.gz
    builds: [cli]
    name_template: >-
      {{ .ProjectName }}_cli_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    allow_different_binary_count: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
