// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	runtime "github.com/go-openapi/runtime"
	mock "github.com/stretchr/testify/mock"
)

// MockClientOption_headscale_service is an autogenerated mock type for the ClientOption type
type MockClientOption_headscale_service struct {
	mock.Mock
}

type MockClientOption_headscale_service_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientOption_headscale_service) EXPECT() *MockClientOption_headscale_service_Expecter {
	return &MockClientOption_headscale_service_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockClientOption_headscale_service) Execute(_a0 *runtime.ClientOperation) {
	_m.Called(_a0)
}

// MockClientOption_headscale_service_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockClientOption_headscale_service_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *runtime.ClientOperation
func (_e *MockClientOption_headscale_service_Expecter) Execute(_a0 interface{}) *MockClientOption_headscale_service_Execute_Call {
	return &MockClientOption_headscale_service_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockClientOption_headscale_service_Execute_Call) Run(run func(_a0 *runtime.ClientOperation)) *MockClientOption_headscale_service_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*runtime.ClientOperation))
	})
	return _c
}

func (_c *MockClientOption_headscale_service_Execute_Call) Return() *MockClientOption_headscale_service_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientOption_headscale_service_Execute_Call) RunAndReturn(run func(*runtime.ClientOperation)) *MockClientOption_headscale_service_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientOption_headscale_service creates a new instance of MockClientOption_headscale_service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientOption_headscale_service(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientOption_headscale_service {
	mock := &MockClientOption_headscale_service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
