// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	tailnet "github.com/awlsring/tailscale-cloud-exit-nodes/internal/pkg/domain/tailnet"
)

// MockTailnet_service is an autogenerated mock type for the Tailnet type
type MockTailnet_service struct {
	mock.Mock
}

type MockTailnet_service_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTailnet_service) EXPECT() *MockTailnet_service_Expecter {
	return &MockTailnet_service_Expecter{mock: &_m.Mock}
}

// Describe provides a mock function with given fields: _a0, _a1
func (_m *MockTailnet_service) Describe(_a0 context.Context, _a1 tailnet.Identifier) (*tailnet.Tailnet, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Describe")
	}

	var r0 *tailnet.Tailnet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tailnet.Identifier) (*tailnet.Tailnet, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tailnet.Identifier) *tailnet.Tailnet); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tailnet.Tailnet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, tailnet.Identifier) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTailnet_service_Describe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Describe'
type MockTailnet_service_Describe_Call struct {
	*mock.Call
}

// Describe is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 tailnet.Identifier
func (_e *MockTailnet_service_Expecter) Describe(_a0 interface{}, _a1 interface{}) *MockTailnet_service_Describe_Call {
	return &MockTailnet_service_Describe_Call{Call: _e.mock.On("Describe", _a0, _a1)}
}

func (_c *MockTailnet_service_Describe_Call) Run(run func(_a0 context.Context, _a1 tailnet.Identifier)) *MockTailnet_service_Describe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(tailnet.Identifier))
	})
	return _c
}

func (_c *MockTailnet_service_Describe_Call) Return(_a0 *tailnet.Tailnet, _a1 error) *MockTailnet_service_Describe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTailnet_service_Describe_Call) RunAndReturn(run func(context.Context, tailnet.Identifier) (*tailnet.Tailnet, error)) *MockTailnet_service_Describe_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: _a0
func (_m *MockTailnet_service) List(_a0 context.Context) ([]*tailnet.Tailnet, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*tailnet.Tailnet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*tailnet.Tailnet, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*tailnet.Tailnet); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tailnet.Tailnet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTailnet_service_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTailnet_service_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockTailnet_service_Expecter) List(_a0 interface{}) *MockTailnet_service_List_Call {
	return &MockTailnet_service_List_Call{Call: _e.mock.On("List", _a0)}
}

func (_c *MockTailnet_service_List_Call) Run(run func(_a0 context.Context)) *MockTailnet_service_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTailnet_service_List_Call) Return(_a0 []*tailnet.Tailnet, _a1 error) *MockTailnet_service_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTailnet_service_List_Call) RunAndReturn(run func(context.Context) ([]*tailnet.Tailnet, error)) *MockTailnet_service_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTailnet_service creates a new instance of MockTailnet_service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTailnet_service(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTailnet_service {
	mock := &MockTailnet_service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
